version: '3.9'

services:
  mongodb:
    image: mongo:7.0.16-jammy
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    restart: always
    ports:
      - 27017:27017

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flaskapi
    restart: always
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
      - MONGODB_DB=usersdb
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=admin
    depends_on:
      - mongodb
    volumes:
      - .:/app
